- name: variables
  hosts: localhost
  vars: #variables declaration
    course: "AWS"
    trainer: "siva"
    Duration: "140hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "hi we are learing {{course}} from trainer {{trainer}} duration {{Duration}}"