- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: installin diff type of packages
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: latest
    loop:
    - ansible
    - mysql
    - nginx 