- name: install and uninstall packages
  hosts: localhost
  become: yes
  tasks:
  - name: installin and uninstall diff type of packages
    ansible.builtin.dnf:
     name: "{{ item.name }}"
     state: "{{item.latest}}"
    loop:
    - { name: 'mysql' , state: 'latest' }
    - { name: 'mysql' , state: 'absent' }
    - { name: 'mysql' , state: 'absent' }