- name: variables prompting
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: please enter your user name
      private: false
    - name: PASSWD
      prompt: please enter unser password
      private: true
  tasks: 
  - name: user access
    ansible.builtin.debug:
     msg:"Hi,your {{USERNAME}}" and {{PASSWD}} is"