- name: print default value
  hosts: localhost
  tasks:
  - name: printing the default value
    ansible.builtin.debug:
     msg: "Hello {{course | default('ansible')}}"

- name: change to upper case
  hosts: localhost
  vars:
   greetings: "Hello world.com"
  tasks:
  - name: converting to upper case
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

- name: change to upper case
  hosts: localhost
  vars:
   greetings: "Hello world.com"
  tasks:
  - name: converting to upper case
    ansible.builtin.debug:
     msg: "{{greetings | lower}}"     

- name: Remove duplicates
  hosts: localhost
  vars:
   number: [1, 2, 3, 3, 4, 4, 5, 5]
  tasks:
  - name: removing duplicates
    ansible.builtin.debug:
     msg: "{{number | unique}}"     

- name: print the min and max
  hosts: localhost
  tasks:
  - name:print the min and mx ages
    ansible.builtin.debug:
     msg: "print min age{{ages | min}} , print max {{ages | max}}"     

