- name: print default value
  hosts: localhost
  tasks:
  - name: printing the default value
    ansible.builtin.debug:
     msg: "Hello {{course | default('ansible')}}"

- name: change to upper case
  hosts: localhost
  vars:
   greetings: "Hello world.com"
  tasks:
  - name: converting to upper case
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

- name: change to upper case
  hosts: localhost
  vars:
   greetings: "Hello world.com"
  tasks:
  - name: converting to upper case
    ansible.builtin.debug:
     msg: "{{greetings | lower}}"     

- name: Remove duplicates
  hosts: localhost
  vars:
   number: [1, 2, 3, 3, 4, 4, 5, 5]
  tasks:
  - name: removing duplicates
    ansible.builtin.debug:
     msg: "{{number | unique}}"     

- name: print the min and max
  hosts: localhost
  vars:
   ages: [25, 36, 48, 47]
  tasks:
  - name: print the min and max ages
    ansible.builtin.debug:
     msg: "min age:{{ ages | min }} ,  maxage: {{ ages | max }}"    

- name: conert dictionary into item/list
  hosts: localhost
  vars:
   MY_Dictionary:
    Name: sivakumar
    course: Devops
    duration: 120hrs
  tasks:
  - name: befores converting to items
    ansible.builtin.debug:
     msg: " befote converting {{MY_Dictionary}}"  
  tasks:
  - name: after converting to items
    ansible.builtin.debug:
     msg: " after converting {{MY_Dictionary | dict2items}}"


